const IMAGES = {
 logoFNHL: require('./FNHL_Logo_2.png'),
 logoANA: require('./ANA_sm.png'),
 logoBOS: require('./BOS_sm.png'),
 logoBUF: require('./BUF_sm.png'),
 logoCAR: require('./CAR_sm.png'),
 logoCBJ: require('./CBJ_sm.png'),
 logoCGY: require('./CGY_sm.png'),
 logoCHI: require('./CHI_sm.png'),
 logoCOL: require('./COL_sm.png'),
 logoDAL: require('./DAL_sm.png'),
 logoDET: require('./DET_sm.png'),
 logoEDM: require('./EDM_sm.png'),
 logoFLA: require('./FLA_sm.png'),
 logoLA: require('./LA_sm.png'),
 logoMIN: require('./MIN_sm.png'),
 logoMON: require('./MON_sm.png'),
 logoNAS: require('./NAS_sm.png'),
 logoNJD: require('./NJD_sm.png'),
 logoNYI: require('./NYI_sm.png'),
 logoNYR: require('./NYR_sm.png'),
 logoOTT: require('./OTT_sm.png'),
 logoPHI: require('./PHI_sm.png'),
 logoPHX: require('./PHX_sm.png'),
 logoPIT: require('./PIT_sm.png'),
 logoSEA: require('./SEA_sm.png'),
 logoSJS: require('./SJS_sm.png'),
 logoSTL: require('./STL_sm.png'),
 logoTB: require('./TB_sm.png'),
 logoTOR: require('./TOR_sm.png'),
 logoVAN: require('./VAN_sm.png'),
 logoVEG: require('./VEG_sm.png'),
 logoWPG: require('./WPG_sm.png'),
 logoWSH: require('./WSH_sm.png'),
}

export default IMAGES;